### ISSUE TITLE
Doesn't work in Chrome browser?

### ISSUE THREAD

**Issue by sgipianobuddha** [no-chris/chord-chart-studio#630]
I've just started using this app. I began in the Safari browser. Then I wanted to use "find & replace" which the Safari browser doesn't support, so I copy/pasted all my files to Chrome browser. This worked nicely, but after I activated the "find and replace" extension, this froze the app to the one file I had open (couldn't select any other files in the side-bar).

**Comment by no-chris** [comment]
Sorry for the late reply and thanks for dropping by. Does the issue persists? What is the "find and replace" extension? Thanks

**Comment by sgipianobuddha** [comment]
https://chrome.google.com/webstore/detail/find-replace/lchlicjgphiemnihicjkgfjddjmlgcdl#:~:text=Find%20Replace&text=A%20simple%20find%20and%20replace,functional%20at%20the%20same%20time.

In Mac’s Safari, I’d have to actually purchase an app to do this…
Here’s how it works in Mac’s Pages app: https://support.apple.com/guide/pages/find-and-replace-text-tan72486d0d/mac#:~:text=You%20can%20search%20for%20specific,is%20included%20in%20the%20search.

I’ve given up trying to do this in either browser.

But maybe it’s something you could add to Chord Chart Studio? 
Makes it easier to make global changes to consistent errors, for example in formatting. Let’s say you’ve written an entire chart and mistakenly typed in the “E minor” chord as “EM” and you wanted to change every instance of “EM” to “Em” without physically editing every single instance. “Find & Replace” allows you to Find every “EM” and instantly replace every iteration with “Em” in one go.

**Comment by no-chris** [comment]
Yes, find and replace functionality would definitely be great but I don't want to give any expectations as for implementation 😅  I don't see that happening short/mid term as there are so many things I would like to do prior to that, such a better song library management with metadata
