### ISSUE TITLE
Render of "chords differ a bit in a repeated section" not working as promised

### ISSUE THREAD

**Issue by sgipianobuddha** [no-chris/chord-chart-studio#632]
The ChordMark manual explains that sections in which the chords differ a bit can simply be adjusted in subsequent sections to show the change.
<img width="733" alt="From the ChordMark manual" src="https://github.com/no-chris/chord-chart-studio/assets/148682967/cdf1329c-9424-4024-bf59-5ce703ea175d">
In this example, however, the "override" doesn't seem to work, as the leftover chords from V1 just get added onto the point in V2 where the change occurs.
<img width="750" alt="See how V2 is slightly shorter than V1" src="https://github.com/no-chris/chord-chart-studio/assets/148682967/9c12a434-5eda-4386-8fd8-9aa3fda98857">
Here's the coding view. What did I do wrong? Do the duplicated (but slightly different) sections need to be the exact same length?
<img width="758" alt="'Edit' view with 'extra' chords circled" src="https://github.com/no-chris/chord-chart-studio/assets/148682967/a38346ee-ab0e-4b14-b34f-49519adb36e4">
Thank you.

**Comment by no-chris** [comment]
Hello,
Could you please paste the song source here to make it easier to understand the issue?
It seems that the time signature are not rendered properly in the screen view, is this the issue? It seems correct in the preview.
Thanks

**Comment by sgipianobuddha** [comment]
Sure. By “song source” I assume you mean the ChordMark code.

I have already by-passed the situation by just not using the #c or #v duplicating feature and simply writing the chords out for every section—as a work-around.

But I continue to come across this problem, where the “unused” chords from the initial section get stacked up just before the edit in the edited duplicate.

Here’s the code. V1 is slightly longer than V2. After the lyric “looking” in V2 is where ChordMark stacks up the “unused” chords from V1 at the end of the line preceding the change.
key B

#i

F#m6 B7.. B..

#v

B B. F#/A#. G#m..

_I am just a poor boy, though my _story's _seldom _told, I have

F# F#7

_Squandered my resistance /(for a) _pocketful of mumbles, such are

B B. F#/A#. G#m..

_Promises / / / _/all _lies and _jest, still a man 

F#.. E.. E.. B.. F# 2/4 F#7 4/4 B %

_ -Hears what he _wants to hear and _disregards the rest_/ / _/ / / / _/ / _/ / / / _/ / / /

#v

(When I) _left my-home and my family I was _no more _than a boy_ in the

_company of strangers, in the _quiet of the railway station

_Running scared/ / / _/ _laying _low, seeking

_out the poorer _quarters where the _ragged people go,_ looking

F#.. E.. B

_for the places _only they would _know / / Lie-la-lie

￼￼

**Comment by no-chris** [comment]
Oh right I got it (I think 😄 )

So basically you would expect:
```
#v
C Am Em G7
_A _line _with some _chords

#v
_Another _line
```

To render as:
```
Verse 1
|C |Am  |Em       |G7    |
 A  line with some chords

Verse 2
|C      |Am  |
 Another line
```

instead of:
```
Verse 1
|C |Am  |Em       |G7    |
 A  line with some chords 

Verse 2
|C      |Am  |Em |G7 |
 Another line

```

Because in the second verse, the lyric line has only 2 chords position markers instead of 4 in the first verse.

Unfortunately this is not how it works. Behind the scenes, when using automatic repeats between sections, there is absolutely no difference between writing:
```
#v
_Another _line
```
and
```
C Am Em G7
_Another _line
```
So in that case, Chord Mark does what it is programmed to do, meaning stacking up chords without position markers at the end of the line. It is actually a feature to avoid having to explicitly write position markers if there are no lyrics attached to them, so you don't have to type things such as:
```
_Yet another _line _ _
```
This is part of the documentation here:

<img width="677" alt="Screenshot 2023-10-29 at 22 04 57" src="https://github.com/no-chris/chord-chart-studio/assets/11467480/41d51577-a23f-47ec-8777-30401d36d5ae">

Which renders as:

<img width="679" alt="Screenshot 2023-10-30 at 21 11 51" src="https://github.com/no-chris/chord-chart-studio/assets/11467480/5a44add0-3bc8-41cb-bbc4-0004ceda50ed">

So what you are doing, e.g. overriding the automatic repeat, is actually the correct thing to do.

Hope this clarifies

**Comment by no-chris** [comment]
Sorry I'm tired and I realise I have misunderstood your issue.

In any case the behaviour seems correct to me, looking at your first screenshot:

- verse 1 has 4 lyrics line
- verse 2 has 5 lyrics lines

So you are actually not overriding the 4th line chords but creating a new one

**Comment by sgipianobuddha** [comment]
Ah okay.
I think I’ve figured out my mistake and a solution. I’ve just made V1 have the same number of lines as V2, then it works—even though there’s a time-signature change in V1 and not in V2, and also one more chord in V1 than V2. Amazing!
So I guess the most important thing is that I ensure to have the same number of lines in each duplicated section.
Thank you for your assistance—I’m learning slowly. (I’m sorry to have kept you up at night about this.)
I appreciate your help and absolutely LOVE your app!
Cheers,
SAM
___________
key B

#i

F#m6 B7.. B..

#v

B B. F#/A#. G#m..

_I am just a poor boy, though my _story's _seldom _told, I have

F# F#7

_Squandered my resistance /(for a) _pocketful of mumbles, such are

B B. F#/A#. G#m..

_Promises / / / _/all _lies and _jest, still a man 

F#.. E.. E.. B.. 

_ -Hears what he _wants to hear and _disregards the rest_/ / 

F# 2/4 F#7 4/4 B %

_/ / / /_/ / _/ / / / _/ / / /

#v

(When I) _left my-home and my family I was _no more _than a boy_ in the

_company of strangers, in the _quiet of the railway station

_Running scared/ / / _/ _laying _low, seeking

_out the poorer _quarters where the _ragged people go,_ looking

F#.. E.. B

_for the places _only they would _know / / Lie-la-lie

￼
