### ISSUE TITLE
Modulation in the middle of a chart doesn't work with Auto-repeat-chords?

### ISSUE THREAD

**Issue by sgipianobuddha** [no-chris/chord-chart-studio#633]
Hi Christophe:
Sam here again with another question.
Why won't Verse 3 auto-repeat with modulated chords?
Even though I state "Key of F" after the Chorus, Verse 3 remains in the key of D like at the top.
What am I doing wrong?
Thanks!
SAM

EDIT VIEW:

key D
#i 
E/D Gm6/D DMaj9 % 
E/D Gm6/D DMaj9 % 
(_1 2 3 4 _1 2 3 4 _1 2 3 4 _1 2) You're just too

#v
D % DMaj7 %
_Good to be true. (4 _1 2) Can't take my _eyes off of you. (4 _1 2) You'd be like
D7 % G %
_Heaven to touch. (4 _1 2) I wanna _hold you so much. (4 _1 2) At long last
Gm % D % 
_Love has arrived. (4 _1 2) And I thank _God I'm alive. (4 _1 2) You're just too
E/D Gm6/D DMaj9 %
_Good to be true. (4 _1 2) Can't take my _eyes off of you. (4 _1 2) Pardon the

#v
_Way that I stare. (4 _1 2) There's nothin' _else to compare. (4 _1 2) The sight of
_You leaves me weak. (4 _1 2) There are no _words left to speak. (4 _1 2) But if you
_Feel like I feel. (4 _1 2) Please let me _know that it's real. (4 _1 2) You're just too
_Good to be true. (4 _1 2) Can't take my _eyes off of you. (4 _1 2 3 4)

#instrumental
Eø. Em. Eø. Em. A7 D+5. D6. D+5. D6. Bm7
Eø. Em. Eø. Em. A7 D+5. D6. D+5. D6. B7#9 
B7#9
(_1) I love you

#c
Em7 Asus F#m7 Bsus.. Bm7..
_Ba-by, and if it's _quite alright, I need you, _Ba-by, to warm the _lonely _night, I love you
Em7 Asus D6 B7#9
_Ba-by, (3 4) _trust in me when I _say: (2 3 4, _1) Oh, pret-ty
Em7 Asus F#m7 Bsus.. Bm7..
_Baby, don't bring me _down, I pray. Oh, pretty _baby, now that I've _found you, _stay and let me 
Em % C9 %
_Love you, ba_-by, let me _love you. (3 4 _1) You're just too 

key F

#v
_Good to be true. (4 _1 2) Can't take my _eyes off of you. (4 _1 2) You'd be like
_Heaven to touch. (4 _1 2) I wanna _hold you so much. (4 _1 2) At long last
_Love has arrived. (4 _1 2) And I thank _God I'm alive. (4 _1 2) You're just too
_Good to be true. (4 _1 2) Can't take my _eyes off of you. (4 _1 2) Pardon the

<img width="676" alt="Screenshot 2023-11-04 at 5 59 51 PM" src="https://github.com/no-chris/chord-chart-studio/assets/148682967/292a2253-2df6-4137-9fcb-2059e959363b">

**Comment by no-chris** [comment]
Hello!

Sorry for the late response

I see your point, the expectation was that setting the key would automatically modulate the repeated chords. Very, nice, I need to think this through.

Actually repeating chords in a different key is something that is not implemented at all. Repeats are always exactly as they were defined in the first place. I thought about this feature a few times, but my idea for a syntax would have been something like:
```
#v +3
```
meaning that the chords of the verse would I been repeated 3 semitones higher.

But that would pollute the syntax and might become really cumbersome especially if you want to write something like 
```
#v +3 x2
```

Actually, I like your idea much better 👍🏻

**Comment by no-chris** [comment]
this behavior will be part of the next release https://github.com/no-chris/chord-mark/pull/638

**Comment by no-chris** [comment]
deployed and available

**Comment by sgipianobuddha** [comment]
Hey Christophe,
Hoping this message finds you well.
I got really busy at the beginning of 2024 (buying a mobile home on six acres of land in northern Virginia and moving from my apartment to there), but I’ve gotten back into writing lyric charts now and just saw what you did with the auto key changing in the middle of a chart.
VERY nice!
I continue to find your app extremely helpful.
Cheers,
SAM

**Comment by no-chris** [comment]
Hey Sam
Nice hearing from you 
Sounds like you have been up to exciting things :)
Glad you like the new feature
Cheers
